<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5LN10rX\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5LN10rX/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container5LN10rX.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container5LN10rX\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container5LN10rX\appAppKernelProdContainer([
    'container.build_hash' => '5LN10rX',
    'container.build_id' => '35be7910',
    'container.build_time' => 1596741945,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5LN10rX');
