<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAu6xnNe\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAu6xnNe/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAu6xnNe.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAu6xnNe\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerAu6xnNe\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Au6xnNe',
    'container.build_id' => 'a7080bdb',
    'container.build_time' => 1596896379,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAu6xnNe');
