<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYgwex5r\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYgwex5r/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYgwex5r.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYgwex5r\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYgwex5r\appDevDebugProjectContainer([
    'container.build_hash' => 'Ygwex5r',
    'container.build_id' => 'c7600248',
    'container.build_time' => 1595949033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYgwex5r');
